<?php
/**
 * Implements hook_schema().
 */
function dhhoasen_schema() {
  $schema = array();
  $schema ['dhhoasen'] = array(
    'description' => 'dhhoasen information',
    'fields' => array(
      'id' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'size' => 'big',
        'description' => 'ID Of dhhoasen'
      )
    ),
    'primary key' => array(
      'id'
    )
  );
  return $schema;
}
